language: node_js
node_js:
  - '6'
  - '7'
  - '8'
  - '10'

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: '6'
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        on:
          tags: true
